version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Shanghai
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    rebase-strategy: auto
    commit-message:
      prefix: deps

  - package-ecosystem: swift
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:15"
      timezone: Asia/Shanghai
    groups:
      swift-packages:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    rebase-strategy: auto
    commit-message:
      prefix: deps
