#!/usr/bin/env bash

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

fail() {
  echo "::error::$1" >&2
  exit 1
}

for file in PRIVACY.md TERMS.md SECURITY.md docs/DATA_FLOW_INVENTORY.md docs/INTERFACE_CONTRACT.md docs/LEGAL_RELEASE_CHECKLIST.md docs/BRAND_ASSET_REVIEW.md docs/COMMERCIAL_LICENSE_SECURITY.md docs/codex-integration-field-notes.md; do
  test -s "$file" || fail "Missing canonical legal/data-flow artifact: $file"
done

require_documented() {
  local pattern="$1"
  local file="$2"
  local label="$3"
  rg -q "$pattern" "$file" || fail "$label is missing from $file"
}

require_documented '127\.0\.0\.1' PRIVACY.md "Local Hook boundary"
require_documented 'api\.manus\.im' PRIVACY.md "Manus third-party flow"
require_documented 'tasks\.sqlite' PRIVACY.md "Local task persistence"
require_documented 'View History' PRIVACY.md "Local history viewing control"
require_documented 'Disconnect All' PRIVACY.md "Bulk local-Hook removal control"
require_documented 'ExitPlanMode' PRIVACY.md "Claude plan-review local processing"
require_documented 'Keychain' PRIVACY.md "API-key storage"
require_documented 'GitHub Releases' PRIVACY.md "Update destination"
require_documented '[Ss]ystem profil' PRIVACY.md "Sparkle profiling behavior"
require_documented 'Notification Center' PRIVACY.md "Notification content flow"
require_documented 'clipboard' PRIVACY.md "User-initiated diagnostics flow"
require_documented 'Cloudflare' PRIVACY.md "Realtime tunnel state"
require_documented 'Local Usage Insights' PRIVACY.md "Opt-in local usage processing"
require_documented 'token_count' PRIVACY.md "Codex usage source"
require_documented 'Qwen Code' PRIVACY.md "Qwen Code local Hook processing"
require_documented 'GitHub Copilot CLI' PRIVACY.md "Copilot CLI local Hook processing"
require_documented 'Kimi Code CLI' PRIVACY.md "Kimi Code CLI local Hook processing"
require_documented 'startup window' PRIVACY.md "Previous-launch readiness health"
require_documented 'does not inspect a crash report' PRIVACY.md "No local crash-report inspection"
require_documented 'raw error descriptions' PRIVACY.md "Unified-log raw-error exclusion"
require_documented 'short-lived OpenAI-signed Codex App Server' PRIVACY.md "Codex Hook trust metadata processing"
require_documented '`hooks/list`' PRIVACY.md "Codex Hook trust protocol disclosure"
require_documented '5,000' PRIVACY.md "Finite local task-history retention"
require_documented '20,000' PRIVACY.md "Finite local progress-history retention"
require_documented 'text is materialized in the app' PRIVACY.md "Persisted-row pre-materialization boundary"
require_documented '`0700`' PRIVACY.md "Private local-history directory permissions"
require_documented '`0600`' PRIVACY.md "Private local-history file permissions"
require_documented 'rejects links, non-regular files' PRIVACY.md "Local-history link/type boundary"
require_documented 'anchors for both the final folder and main file' PRIVACY.md "Local-history directory and file anchors"
require_documented 'before and after every history' PRIVACY.md "Runtime SQLite operation boundary"
require_documented 'full SQLite Connection lifetime' PRIVACY.md "Runtime SQLite anchor lifetime"
require_documented 'at most 4 MiB' PRIVACY.md "Managed Hook config read bound"
require_documented 'symbolic links, hard links' PRIVACY.md "Managed Hook link boundary"
require_documented 'New configuration files use mode `0600`' PRIVACY.md "Managed Hook private creation mode"

require_documented 'MIT License' TERMS.md "Repository license relationship"
require_documented 'third-part' TERMS.md "Third-party service terms"
require_documented 'Agent actions' TERMS.md "Agent approval risk"
require_documented 'trial' TERMS.md "Commercial status"
require_documented 'zero trust anchors' docs/COMMERCIAL_LICENSE_SECURITY.md "Disabled commercial trust state"
require_documented 'no customer PII' docs/COMMERCIAL_LICENSE_SECURITY.md "Privacy-minimal license schema"
require_documented 'all nine Agent marks' docs/BRAND_ASSET_REVIEW.md "Complete Agent brand review boundary"
require_documented 'provenanceReview: reviewed' docs/BRAND_ASSET_REVIEW.md "Brand provenance release requirement"
require_documented 'trademarkReview: approved' docs/BRAND_ASSET_REVIEW.md "Brand trademark release requirement"
require_documented 'not legal advice' docs/BRAND_ASSET_REVIEW.md "Brand review legal limitation"
require_documented 'fails before loading Release credentials' docs/LEGAL_RELEASE_CHECKLIST.md "Fail-closed commercial brand review gate"

for source_fact in \
  '127\.0\.0\.1' \
  'api\.manus\.im' \
  'tasks\.sqlite' \
  'manus_api_key' \
  'Cloudflare' \
  'Sparkle' \
  'Notification Center' \
  'Copy / Save Diagnostics'; do
  require_documented "$source_fact" docs/DATA_FLOW_INVENTORY.md "Known data flow: $source_fact"
done
require_documented 'ManagedConfigFile' docs/DATA_FLOW_INVENTORY.md "Managed Hook transaction source map"
require_documented 'Local Agent Hook request authorization' docs/DATA_FLOW_INVENTORY.md "Local Hook request-authorization data flow"
require_documented 'X-Dev-Island-Hook: v1' docs/DATA_FLOW_INVENTORY.md "Local Hook non-simple request marker"
require_documented '256-bit random `X-Dev-Island-Authorization`' docs/DATA_FLOW_INVENTORY.md "Local Hook cross-user credential"
require_documented 'local-hook-authorization\.header' docs/DATA_FLOW_INVENTORY.md "Local Hook private credential file"
require_documented 'never enters Agent config, plugin source, argv, logs, SQLite or diagnostics' docs/DATA_FLOW_INVENTORY.md "Local Hook credential non-disclosure"
require_documented '256-bit random authorization' PRIVACY.md "Local Hook authorization privacy disclosure"
require_documented 'local-hook-authorization\.header' PRIVACY.md "Local Hook authorization persistence disclosure"

require_documented 'CommercialLicenseVerifier' docs/DATA_FLOW_INVENTORY.md "Commercial license data-flow state"
require_documented 'CommercialLicenseDocumentStore' docs/DATA_FLOW_INVENTORY.md "Commercial license storage source map"
require_documented 'CommercialLicenseActivation' docs/DATA_FLOW_INVENTORY.md "Commercial activation source map"
require_documented '16–128 byte activation code' docs/DATA_FLOW_INVENTORY.md "Commercial activation code boundary"
require_documented 'erased with `memset_s`' docs/DATA_FLOW_INVENTORY.md "Commercial activation secret-memory lifecycle"
require_documented 'commercial_license_v1' docs/DATA_FLOW_INVENTORY.md "Commercial license Keychain account"
require_documented 'WhenUnlockedThisDeviceOnly' docs/DATA_FLOW_INVENTORY.md "Commercial license device-only accessibility"
require_documented 'non-synchronizable' docs/DATA_FLOW_INVENTORY.md "Commercial license non-sync behavior"
require_documented 'View History' docs/DATA_FLOW_INVENTORY.md "Local history viewing data flow"
require_documented '128 live sessions' docs/DATA_FLOW_INVENTORY.md "Per-connector live-session bound"
require_documented 'newest 5,000 task rows' docs/DATA_FLOW_INVENTORY.md "Finite local task-history data flow"
require_documented '20,000 progress rows' docs/DATA_FLOW_INVENTORY.md "Finite local progress-history data flow"
require_documented 'before SQLite\.swift materializes text' docs/DATA_FLOW_INVENTORY.md "Persisted-row read boundary"
require_documented 'owner-only `0700`' docs/DATA_FLOW_INVENTORY.md "Private SQLite directory data flow"
require_documented 'owner-only `0600`' docs/DATA_FLOW_INVENTORY.md "Private SQLite file data flow"
require_documented 'anchor both final-directory and main-file' docs/DATA_FLOW_INVENTORY.md "SQLite directory and file identity anchors"
require_documented 'full Connection lifetime' docs/DATA_FLOW_INVENTORY.md "Runtime SQLite anchor lifetime"
require_documented 'before and after every history read, write, retention pass' docs/DATA_FLOW_INVENTORY.md "Runtime SQLite operation boundary"
require_documented 'terminally disables the active history-store instance' docs/DATA_FLOW_INVENTORY.md "Runtime SQLite terminal-failure behavior"
require_documented 'Disconnect All' docs/DATA_FLOW_INVENTORY.md "Bulk local-Hook removal data flow"
require_documented 'ExitPlanMode' docs/DATA_FLOW_INVENTORY.md "Claude plan-review data flow"
require_documented 'Local Codex usage insight' docs/DATA_FLOW_INVENTORY.md "Opt-in local usage data flow"
require_documented 'Qwen Code lifecycle and permission hooks' docs/DATA_FLOW_INVENTORY.md "Qwen Code Preview data flow"
require_documented 'GitHub Copilot CLI lifecycle and attention hooks' docs/DATA_FLOW_INVENTORY.md "Copilot CLI Preview data flow"
require_documented 'Kimi Code CLI lifecycle and approval-attention hooks' docs/DATA_FLOW_INVENTORY.md "Kimi Code CLI Preview data flow"
require_documented 'Previous launch health' docs/DATA_FLOW_INVENTORY.md "Local launch-health data flow"
require_documented 'devIsland\.launchHealth\.didStart' docs/DATA_FLOW_INVENTORY.md "Launch-health start marker"
require_documented 'devIsland\.launchHealth\.startupReady' docs/DATA_FLOW_INVENTORY.md "Launch-health ready marker"
require_documented 'devIsland\.launchHealth\.schemaVersion' docs/DATA_FLOW_INVENTORY.md "Launch-health schema marker"
require_documented 'devIsland\.launchHealth\.consecutiveStartupInterruptions' docs/DATA_FLOW_INVENTORY.md "Launch-health bounded count"
require_documented 'devIsland\.launchHealth\.cleanExit.*migration-only' docs/DATA_FLOW_INVENTORY.md "Launch-health legacy migration boundary"
require_documented 'raw error descriptions are prohibited by CI' docs/DATA_FLOW_INVENTORY.md "Unified-log privacy gate"
require_documented 'Configured' docs/DATA_FLOW_INVENTORY.md "Codex config-versus-trust boundary"
require_documented 'Codex Hook trust verification' docs/DATA_FLOW_INVENTORY.md "Codex trust-probe data flow"
require_documented '2 MiB' docs/DATA_FLOW_INVENTORY.md "Codex trust-probe response bound"
require_documented 'OpenAI-signed `com.openai.codex`' docs/DATA_FLOW_INVENTORY.md "Codex trust-probe binary origin"
require_documented 'review-and-trust-hooks' docs/codex-integration-field-notes.md "Official Codex Hook trust source"
require_documented '`hooks/list`' docs/codex-integration-field-notes.md "Documented Codex App Server option"
require_documented 'Shipping bounded App Server trust probe' docs/codex-integration-field-notes.md "Shipping Codex trust-probe boundary"
require_documented 'No public API was found' docs/codex-integration-field-notes.md "Unsupported Codex Cloud monitoring boundary"

require_documented '版本: v6\.59\.0' docs/INTERFACE_CONTRACT.md "Current interface-contract version"
require_documented 'Manus 签名窗口重放与终态单调性' docs/INTERFACE_CONTRACT.md "Manus replay-window contract"
require_documented 'Manus replay 真实 HTTP transport 回归' docs/INTERFACE_CONTRACT.md "Manus replay live-HTTP test contract"
require_documented 'Production 公开构造必须始终使用固定 1,024' docs/INTERFACE_CONTRACT.md "Manus production replay capacity contract"
require_documented '1,024 个仍在有效签名窗口内的 ID' docs/INTERFACE_CONTRACT.md "Manus replay capacity contract"
require_documented 'HTTP 503' docs/INTERFACE_CONTRACT.md "Manus replay saturation response contract"
require_documented 'replay window containing at most 1,024' PRIVACY.md "English Manus replay-window disclosure"
require_documented '最多 1,024 个有限 event ID' PRIVACY.md "Chinese Manus replay-window disclosure"
require_documented 'full live replay window returns 503' docs/DATA_FLOW_INVENTORY.md "Manus replay saturation data flow"
require_documented 'Completed/Failed cannot regress to Waiting' docs/DATA_FLOW_INVENTORY.md "Manus terminal-state data flow"
require_documented 'Plan Review Markdown 单次后台渲染' docs/INTERFACE_CONTRACT.md "Plan Review off-main rendering contract"
require_documented '262,144 UTF-8' docs/INTERFACE_CONTRACT.md "Plan Review Markdown byte contract"
require_documented '512 个块' docs/INTERFACE_CONTRACT.md "Plan Review SwiftUI block bound"
require_documented 'once per request in an on-device detached worker' docs/DATA_FLOW_INVENTORY.md "Plan Review detached rendering data flow"
require_documented 'at most 512 complete blocks' docs/DATA_FLOW_INVENTORY.md "Plan Review block-bound data flow"
require_documented '262,144 UTF-8' PRIVACY.md "English Plan Review byte disclosure"
require_documented 'at most 512 complete blocks' PRIVACY.md "English Plan Review block disclosure"
require_documented '最多 512 个完整块' PRIVACY.md "Chinese Plan Review block disclosure"
require_documented 'Plan Review render isolation' docs/PERFORMANCE_QA.md "Plan Review rendering performance QA"
require_documented 'Thread\.isMainThread == false' docs/PERFORMANCE_QA.md "Plan Review real-thread assertion"
require_documented '展开面板叶子时钟隔离' docs/INTERFACE_CONTRACT.md "Panel leaf-clock isolation contract"
require_documented 'Panel clock leaf isolation' docs/PERFORMANCE_QA.md "Panel leaf-clock performance QA"
require_documented 'Settings Agent Hook 配置 I/O 主线程隔离' docs/INTERFACE_CONTRACT.md "Settings Agent configuration I/O contract"
require_documented 'Welcome 连接配置操作所有权' docs/INTERFACE_CONTRACT.md "Welcome Agent configuration operation contract"
require_documented 'LocalAgentConfigurationExecutor.*detached worker' docs/INTERFACE_CONTRACT.md "Settings detached configuration executor"
require_documented 'Local Agent configuration presentation I/O' docs/DATA_FLOW_INVENTORY.md "Settings Agent configuration presentation data flow"
require_documented 'MainActor-to-non-main execution' docs/DATA_FLOW_INVENTORY.md "Settings non-main execution evidence"
require_documented 'on-device background worker' PRIVACY.md "English Settings configuration worker disclosure"
require_documented 'do not block the interface' PRIVACY.md "English Settings main-thread disclosure"
require_documented '本机后台 worker' PRIVACY.md "Chinese Settings configuration worker disclosure"
require_documented '不会阻塞界面' PRIVACY.md "Chinese Settings main-thread disclosure"
require_documented 'Settings Agent configuration responsiveness' docs/PERFORMANCE_QA.md "Settings configuration responsiveness QA"
require_documented 'Settings Agent 配置全局操作所有权' docs/INTERFACE_CONTRACT.md "Settings cross-pane Agent mutation contract"
require_documented 'Settings Agent mutation ownership across panes' docs/PERFORMANCE_QA.md "Settings cross-pane mutation QA"
require_documented 'one owner across every pane' docs/DATA_FLOW_INVENTORY.md "Settings cross-pane mutation data flow"
require_documented 'one in-memory mutation owner' PRIVACY.md "English Settings cross-pane mutation disclosure"
require_documented '页面切换层之上保留一个仅内存的 mutation owner' PRIVACY.md "Chinese Settings cross-pane mutation disclosure"
require_documented 'Welcome connection operation ownership' docs/PERFORMANCE_QA.md "Welcome configuration responsiveness QA"
require_documented 'Support 诊断导出 I/O 主线程隔离' docs/INTERFACE_CONTRACT.md "Support diagnostics I/O isolation contract"
require_documented 'SupportDiagnosticsIOExecutor.*detached worker' docs/INTERFACE_CONTRACT.md "Support diagnostics detached executor"
require_documented 'MainActor-to-non-main diagnostic execution' docs/DATA_FLOW_INVENTORY.md "Support diagnostics non-main data flow"
require_documented 'transaction run in an on-device background worker' PRIVACY.md "English diagnostic background-worker disclosure"
require_documented '诊断准备.*本机后台 worker' PRIVACY.md "Chinese diagnostic background-worker disclosure"
require_documented 'Support diagnostics responsiveness' docs/PERFORMANCE_QA.md "Support diagnostics responsiveness QA"
require_documented 'Settings and Welcome perform' PRIVACY.md "English Welcome configuration worker disclosure"
require_documented 'Settings 与 Welcome' PRIVACY.md "Chinese Welcome configuration worker disclosure"
require_documented 'Thread\.isMainThread == false' docs/PERFORMANCE_QA.md "Settings configuration real-thread assertion"
require_documented '商业政策审批记录输入边界' docs/INTERFACE_CONTRACT.md "Commercial policy input boundary"
require_documented 'last-key-wins' docs/INTERFACE_CONTRACT.md "Commercial policy duplicate-key ambiguity boundary"
require_documented 'decisionState: required' docs/INTERFACE_CONTRACT.md "Commercial policy remains unapproved"
require_documented 'Welcome 编辑栏几何' docs/INTERFACE_CONTRACT.md "Welcome editorial geometry contract"
require_documented '32pt.*264pt.*28pt.*404pt' docs/INTERFACE_CONTRACT.md "Welcome fixed-width composition"
require_documented '权威测试 SwiftPM 构建图隔离' docs/INTERFACE_CONTRACT.md "Authoritative SwiftPM test-graph isolation contract"
require_documented '\.build/tests-authoritative' docs/INTERFACE_CONTRACT.md "Dedicated authoritative test scratch"
require_documented '准确 66 次调用' docs/INTERFACE_CONTRACT.md "Deterministic authoritative test invocation count"
require_documented 'swift test.*绕过' docs/INTERFACE_CONTRACT.md "Workflow direct-test bypass boundary"
require_documented '权威测试单写者锁' docs/INTERFACE_CONTRACT.md "Authoritative test single-writer contract"
require_documented 'tests-authoritative\.lock' docs/INTERFACE_CONTRACT.md "Authoritative test lock path"
require_documented '/usr/bin/lockf -s -t 0 9' docs/INTERFACE_CONTRACT.md "Non-waiting BSD descriptor lock"
require_documented '第二个权威入口.*swift.*命令前退出' docs/INTERFACE_CONTRACT.md "Contended test graph fails before Swift"
require_documented 'Maintainer authoritative test ownership' docs/DATA_FLOW_INVENTORY.md "Authoritative test lock data-flow boundary"
require_documented 'No content: one fixed zero-byte lock file' docs/DATA_FLOW_INVENTORY.md "Authoritative lock contains no data"
require_documented 'GitHub 仓库审计失败分类与诊断隐私' docs/INTERFACE_CONTRACT.md "GitHub audit failure-classification contract"
require_documented 'GitHub API network unavailable' docs/INTERFACE_CONTRACT.md "Low-cardinality GitHub network failure"
require_documented '1 byte–64 KiB' docs/INTERFACE_CONTRACT.md "Bounded GitHub API diagnostic classification"
require_documented '原始错误不得回显' docs/INTERFACE_CONTRACT.md "GitHub API raw-diagnostic exclusion"
require_documented 'connection reset.*HTTP 401.*HTTP 403.*HTTP 404' docs/INTERFACE_CONTRACT.md "GitHub API classification fixtures"
require_documented 'Dock 重试与进程夹具调度隔离' docs/INTERFACE_CONTRACT.md "Deterministic Dock and process-fixture scheduling contract"
require_documented 'production 默认 timeout 继续固定为 3 秒' docs/INTERFACE_CONTRACT.md "Production Codex timeout isolation"
require_documented 'FixtureError\.pidNotPublished' docs/INTERFACE_CONTRACT.md "Explicit process-fixture PID failure"
require_documented 'macOS 状态菜单实时摘要与隐私边界' docs/INTERFACE_CONTRACT.md "Live status-menu contract"
require_documented 'withObservationTracking' docs/INTERFACE_CONTRACT.md "Event-driven status-menu refresh contract"
require_documented '任务标题、Session ID、路径' docs/INTERFACE_CONTRACT.md "Status-menu privacy boundary"
require_documented '三种 App 构建风味的可执行产物边界' docs/INTERFACE_CONTRACT.md "Artifact-level build-flavor contract"
require_documented '18 个' docs/INTERFACE_CONTRACT.md "Per-marker build-flavor negative matrix"
require_documented 'Maintainer build-flavor executable inspection' docs/DATA_FLOW_INVENTORY.md "Build-flavor executable data flow"
require_documented 'No raw executable strings' docs/DATA_FLOW_INVENTORY.md "Build-flavor raw-string exclusion"
require_documented 'fixed build-flavor markers' PRIVACY.md "English build-flavor inspection disclosure"
require_documented '六个固定构建风味标记' PRIVACY.md "Chinese build-flavor inspection disclosure"
require_documented '离线法律文件与签名 App 字节绑定' docs/INTERFACE_CONTRACT.md "Offline bundled legal-document contract"
require_documented '10 个负向用例' docs/INTERFACE_CONTRACT.md "Legal-document attack-fixture contract"
require_documented 'App 内法律资源 descriptor 原子读取边界' docs/INTERFACE_CONTRACT.md "Runtime legal-document descriptor contract"
require_documented 'O_RDONLY.*O_NOFOLLOW.*O_CLOEXEC.*O_NONBLOCK' docs/INTERFACE_CONTRACT.md "Runtime legal-document open flags"
require_documented 'dev/inode/mode/nlink/size/mtime/ctime' docs/INTERFACE_CONTRACT.md "Runtime legal-document identity revalidation"
require_documented 'Bundled Privacy / Terms reading' docs/DATA_FLOW_INVENTORY.md "Bundled legal-document data flow"
require_documented 'descriptor-backed, no-follow.*1–512 KiB' docs/DATA_FLOW_INVENTORY.md "Runtime legal-document bounded data flow"
require_documented 'PR CI hermetic App 真实启动与正常退出' docs/INTERFACE_CONTRACT.md "Hermetic PR launch-smoke contract"
require_documented 'NSRunningApplication.*terminate' docs/INTERFACE_CONTRACT.md "Exact-PID normal App termination contract"
require_documented '8 个一秒存活样本' docs/INTERFACE_CONTRACT.md "Eight-sample launch survival contract"
require_documented 'Maintainer hermetic App launch and performance sampling' docs/DATA_FLOW_INVENTORY.md "Hermetic maintainer launch-smoke data flow"
require_documented 'eight bounded CPU/RSS samples' PRIVACY.md "English hermetic launch-smoke disclosure"
require_documented '八个有界 CPU/RSS 样本' PRIVACY.md "Chinese hermetic launch-smoke disclosure"
require_documented 'Performance 证据文件 descriptor 所有权' docs/INTERFACE_CONTRACT.md "Atomic performance-evidence file ownership contract"
require_documented 'noclobber.*descriptor 7/8/9' docs/INTERFACE_CONTRACT.md "Exclusive performance-evidence descriptor set"
require_documented 'RDONLY.*NOFOLLOW.*NONBLOCK' docs/INTERFACE_CONTRACT.md "No-follow performance CSV snapshot"
require_documented 'Performance readiness App-log 原子读取' docs/INTERFACE_CONTRACT.md "Atomic readiness App-log read contract"
require_documented 'Performance 输入 App 私有快照与执行身份' docs/INTERFACE_CONTRACT.md "Frozen Performance App execution contract"
require_documented '真正进入.*6-Mach-O.*launch' docs/INTERFACE_CONTRACT.md "Private-only Performance App launch contract"
require_documented 'selected_executable_sha256' docs/INTERFACE_CONTRACT.md "Selected Performance App summary hash"
require_documented 'isolated_app_snapshot=true' docs/INTERFACE_CONTRACT.md "Performance App isolation summary binding"
require_documented 'FIFO.*malformed or duplicate.*reverse/out-of-window' docs/DATA_FLOW_INVENTORY.md "Readiness snapshot failure classes"
require_documented 'random private `0700` sampler root' docs/DATA_FLOW_INVENTORY.md "Private Performance App snapshot data flow"
require_documented 'selected-source replacement' docs/DATA_FLOW_INVENTORY.md "Selected Performance App replacement failure"
require_documented 'current-user `0600` single-link descriptors' PRIVACY.md "English performance-evidence file boundary disclosure"
require_documented '当前用户 `0600` 单硬链接 descriptor' PRIVACY.md "Chinese performance-evidence file boundary disclosure"
require_documented 'App-log writer identity.*malformed or duplicate' PRIVACY.md "English bounded readiness snapshot disclosure"
require_documented 'writer 身份绑定的同类私有快照' PRIVACY.md "Chinese bounded readiness snapshot disclosure"
require_documented 'malformed/重复 marker' PRIVACY.md "Chinese strict readiness parser disclosure"
require_documented "sampler's random private" PRIVACY.md "English private Performance App snapshot disclosure"
require_documented '`0700` directory' PRIVACY.md "English private Performance App directory disclosure"
require_documented '来源被替换时不发布 summary' PRIVACY.md "Chinese Performance App replacement disclosure"
require_documented 'PR CI Performance summary 进程内交付' docs/INTERFACE_CONTRACT.md "In-memory PR performance summary contract"
require_documented 'workflow 禁止再对' docs/INTERFACE_CONTRACT.md "Post-exit public summary reopen prohibition"
require_documented 'dev-island-launch-smoke\.summary\.txt' docs/INTERFACE_CONTRACT.md "Public performance summary path contract"
require_documented '本地 listener 无副作用 transport 夹具' docs/INTERFACE_CONTRACT.md "Hermetic local-listener transport contract"
require_documented '零 stderr' docs/INTERFACE_CONTRACT.md "Hermetic local-listener silent diagnostic contract"
require_documented 'App SwiftPM 外置 scratch 边界' docs/INTERFACE_CONTRACT.md "External App SwiftPM scratch contract"
require_documented 'prepare-scratch' docs/INTERFACE_CONTRACT.md "Validated external SwiftPM scratch boundary"
require_documented 'Maintainer external SwiftPM App scratch' docs/DATA_FLOW_INVENTORY.md "External SwiftPM scratch data flow"
require_documented 'no Agent configuration' docs/DATA_FLOW_INVENTORY.md "External SwiftPM scratch product-data exclusion"
require_documented 'bounded sampler-stdout shell variable' docs/DATA_FLOW_INVENTORY.md "In-process performance acceptance data flow"
require_documented 'Production App hermetic 真实启动门禁' docs/INTERFACE_CONTRACT.md "Production App launch-smoke contract"
require_documented '精确参数\+环境双重 opt-in' docs/INTERFACE_CONTRACT.md "Production launch-smoke dual opt-in boundary"
require_documented 'readiness 后及每个样本.*没有网络 socket' docs/INTERFACE_CONTRACT.md "Production launch-smoke repeated network isolation"
require_documented 'Maintainer Production App hermetic launch smoke' docs/DATA_FLOW_INVENTORY.md "Production launch-smoke data flow"
require_documented 'every one-second sample verify no network socket' docs/DATA_FLOW_INVENTORY.md "Production launch-smoke repeated isolation data flow"
require_documented 'maintainer-only `production-launch-smoke`' PRIVACY.md "English Production launch-smoke disclosure"
require_documented '每一秒只检查精确 PID 是否出现网络 socket' PRIVACY.md "Chinese Production launch-smoke disclosure"
require_documented 'real Production Bundle has a maintainer-only hermetic launch mode' docs/LEGAL_RELEASE_CHECKLIST.md "Production launch-smoke release gate"
require_documented 'does not reopen the runner-temporary' PRIVACY.md "English in-memory performance summary disclosure"
require_documented 'producer 退出后不再重开 runner 临时' PRIVACY.md "Chinese in-memory performance summary disclosure"
require_documented 'exact, read-only copies of this notice' PRIVACY.md "English bundled legal-document disclosure"
require_documented '精确只读副本' PRIVACY.md "Chinese bundled legal-document disclosure"
require_documented 'Current Support actions are preceded by offline Privacy / Terms entries' docs/LEGAL_RELEASE_CHECKLIST.md "Current in-app legal entry gate"
require_documented 'Manus 真实账号验收证据边界' docs/INTERFACE_CONTRACT.md "Manus live-evidence contract"
require_documented 'O_NOFOLLOW.*1 byte–64 KiB' docs/INTERFACE_CONTRACT.md "Bounded no-follow Manus transcript validation"
require_documented '只有 CLI exit 0.*--require-accepted' docs/INTERFACE_CONTRACT.md "Fail-closed Manus accepted marker"
require_documented 'Manus 验收编译输入闭包' docs/INTERFACE_CONTRACT.md "Manus complete build-input closure"
require_documented 'ignored local file' docs/INTERFACE_CONTRACT.md "Dependency checkout contamination boundary"
require_documented 'TOOLCHAIN_BEFORE/AFTER_BUILD' docs/INTERFACE_CONTRACT.md "Manus toolchain stability evidence"
require_documented 'GitHub Workflow 内嵌 Shell 语法边界' docs/INTERFACE_CONTRACT.md "Workflow run-shell syntax contract"
require_documented '`/bin/bash -n`' docs/INTERFACE_CONTRACT.md "Non-executing workflow Bash parser"
require_documented '同时验证 `ci\.yml` 与 `release\.yml`' docs/INTERFACE_CONTRACT.md "Both workflows checked before tagged execution"
require_documented 'GitHub Workflow YAML 结构歧义边界' docs/INTERFACE_CONTRACT.md "Workflow YAML ambiguity contract"
require_documented 'exactly one YAML document' docs/INTERFACE_CONTRACT.md "Single-document workflow boundary"
require_documented '`on` 与 `true`' docs/INTERFACE_CONTRACT.md "Resolved duplicate workflow-key boundary"
require_documented '20,000 个 AST node' docs/INTERFACE_CONTRACT.md "Bounded workflow YAML structure"
require_documented 'GitHub Workflow 有效 Shell 解析边界' docs/INTERFACE_CONTRACT.md "Workflow effective-shell contract"
require_documented 'step > job defaults > workflow defaults' docs/INTERFACE_CONTRACT.md "Workflow shell precedence contract"
require_documented '精确 `bash` 或 `/bin/bash`' docs/INTERFACE_CONTRACT.md "Exact reviewed workflow shells"
require_documented '仓库脚本无执行语法闭包' docs/INTERFACE_CONTRACT.md "Repository script syntax-closure contract"
require_documented '43 个 Bash 与 15 个 Ruby' docs/INTERFACE_CONTRACT.md "Complete current repository script closure"
require_documented '前半段写 marker 的命令仍会先执行' docs/INTERFACE_CONTRACT.md "Bash partial-execution threat"
require_documented 'Swift 脚本 stdin-only Parse 闭包' docs/INTERFACE_CONTRACT.md "Swift script parse-closure contract"
require_documented '43 Bash \+ 15 Ruby \+ 5 Swift' docs/INTERFACE_CONTRACT.md "Complete current three-language script closure"
require_documented '`/usr/bin/swiftc -parse -`' docs/INTERFACE_CONTRACT.md "Non-executing Swift parser"
require_documented 'App 构建输出与原子发布边界' docs/INTERFACE_CONTRACT.md "Atomic App build-output contract"
require_documented 'app-build-output-boundary\.rb prepare' docs/INTERFACE_CONTRACT.md "Caller-controlled build-directory boundary"
require_documented '本地 Agent Loopback 浏览器请求边界' docs/INTERFACE_CONTRACT.md "Local Hook browser-request contract"
require_documented 'Access-Control-Allow-Origin' docs/INTERFACE_CONTRACT.md "Local Hook CORS denial contract"
require_documented '本地 CLI 版本探针调度稳定性' docs/INTERFACE_CONTRACT.md "Local CLI probe stability contract"
require_documented '20 轮，共启动' docs/INTERFACE_CONTRACT.md "Local CLI probe CI stress count"
require_documented '本地准备度重试语义与视觉层级' docs/INTERFACE_CONTRACT.md "Readiness retry presentation contract"
require_documented '禁止计入' docs/INTERFACE_CONTRACT.md "Transient checks excluded from setup-action count"
require_documented 'tmux 后台子进程清理调度稳定性' docs/INTERFACE_CONTRACT.md "tmux cleanup stability contract"
require_documented 'descendant 清理 20 轮' docs/INTERFACE_CONTRACT.md "tmux cleanup PR stress count"
require_documented '解锁性能证据与显示会话判定' docs/INTERFACE_CONTRACT.md "Unlocked performance evidence contract"
require_documented 'kCGSSessionOnConsoleKey=true' docs/INTERFACE_CONTRACT.md "Active-console display-session proof"
require_documented 'screen_state_initial=unlocked' docs/INTERFACE_CONTRACT.md "Performance summary initial screen state"
require_documented 'Settings 控件节奏与视觉证据' docs/INTERFACE_CONTRACT.md "Settings control-rhythm contract"
require_documented 'switch 固定在卡片右边线' docs/INTERFACE_CONTRACT.md "Localized Settings switch alignment"
require_documented 'Production 更新页版本号只允许来自 App Bundle' docs/INTERFACE_CONTRACT.md "Production update-version source"
require_documented '自动更新发布私钥进程边界' docs/INTERFACE_CONTRACT.md "Sparkle release-key process boundary"
require_documented '`env -i`' docs/INTERFACE_CONTRACT.md "Sparkle generator minimal environment"
require_documented 'PR CI 脱敏诊断文件边界' docs/INTERFACE_CONTRACT.md "PR CI diagnostic file-boundary contract"
require_documented 'schema v2 以低基数 `sourceStatus`' docs/INTERFACE_CONTRACT.md "Bounded CI diagnostic source status"
require_documented '本地 Agent 双向 Hook 交付顺序' docs/INTERFACE_CONTRACT.md "Synchronous local-action ordering contract"
require_documented '先 `await` lifecycle 交付' docs/INTERFACE_CONTRACT.md "Lifecycle-before-action delivery order"
require_documented 'Maintainer PR CI diagnostics' docs/DATA_FLOW_INVENTORY.md "Maintainer CI diagnostic data flow"
require_documented 'does not collect data from a' PRIVACY.md "CI diagnostics exclude installed-App collection"
require_documented '两个脱敏文件组成的 artifact' PRIVACY.md "Chinese CI diagnostic retention notice"
require_documented 'Maintainer workflow shell validation' docs/DATA_FLOW_INVENTORY.md "Maintainer workflow syntax data flow"
require_documented 'No Secret value or installed-App data is read' docs/DATA_FLOW_INVENTORY.md "Workflow syntax validator data exclusion"
require_documented 'duplicate/resolved-colliding mapping keys' docs/DATA_FLOW_INVENTORY.md "Workflow YAML ambiguity data boundary"
require_documented 'workflow/job `defaults.run.shell`' docs/DATA_FLOW_INVENTORY.md "Workflow inherited-shell data boundary"
require_documented 'Maintainer repository script syntax validation' docs/DATA_FLOW_INVENTORY.md "Repository script syntax data flow"
require_documented 'No repository script is executed' docs/DATA_FLOW_INVENTORY.md "Repository script no-execution boundary"
require_documented '43 Bash \+ 15 Ruby \+ 5 Swift' docs/DATA_FLOW_INVENTORY.md "Three-language repository script inventory"
require_documented 'workflow YAML and Bash `run` steps' PRIVACY.md "English workflow syntax privacy notice"
require_documented 'ambiguous duplicate or multi-document YAML' PRIVACY.md "English workflow ambiguity privacy notice"
require_documented 'effective workflow/job/step shell' PRIVACY.md "English effective-shell privacy notice"
require_documented '静态解析仓库内的 workflow YAML' PRIVACY.md "Chinese workflow syntax privacy notice"
require_documented '重复键或多文档 YAML' PRIVACY.md "Chinese workflow ambiguity privacy notice"
require_documented 'workflow/job/step 的有效 shell' PRIVACY.md "Chinese effective-shell privacy notice"
require_documented 'all repository Bash, Ruby, and Swift scripts' PRIVACY.md "English repository script syntax privacy notice"
require_documented '全部仓库 Bash、Ruby 与 Swift 脚本' PRIVACY.md "Chinese repository script syntax privacy notice"
require_documented 'polling-only 模式提升为 `\.connected`' docs/INTERFACE_CONTRACT.md "Manus realtime downgrade contract"
require_documented 'Maintainer Manus live-acceptance evidence' docs/DATA_FLOW_INVENTORY.md "Maintainer Manus acceptance evidence flow"
require_documented 'maintainer-only live-acceptance' PRIVACY.md "English Manus evidence privacy notice"
require_documented '维护者主动运行的真实验收包装器' PRIVACY.md "Chinese Manus evidence privacy notice"
require_documented '旧结果不得' docs/INTERFACE_CONTRACT.md "Manus stale-poll suppression contract"
require_documented 'clearAPIKey\(\) async throws' docs/INTERFACE_CONTRACT.md "Manus disconnect integrity contract"
require_documented 'CommercialLicenseDocumentStoreError' docs/INTERFACE_CONTRACT.md "Commercial license storage error API"
require_documented 'CommercialLicenseDocumentStore' docs/INTERFACE_CONTRACT.md "Commercial license storage API"
require_documented 'importDocument\(' docs/INTERFACE_CONTRACT.md "Verified commercial license import API"
require_documented 'evaluateStored\(' docs/INTERFACE_CONTRACT.md "Stored commercial license evaluation API"
require_documented 'public func delete\(\) throws' docs/INTERFACE_CONTRACT.md "Commercial license deletion API"
require_documented 'commercial_license_v1' docs/INTERFACE_CONTRACT.md "Commercial license Keychain account contract"
require_documented 'WhenUnlockedThisDeviceOnly' docs/INTERFACE_CONTRACT.md "Commercial license device-only contract"
require_documented 'verify-before-save' docs/INTERFACE_CONTRACT.md "Commercial license fail-closed import contract"
require_documented 'CommercialActivationCode' docs/INTERFACE_CONTRACT.md "Commercial activation code API"
require_documented '`memset_s` 主动清零' docs/INTERFACE_CONTRACT.md "Commercial activation code erasure contract"
require_documented 'CommercialActivationTransport' docs/INTERFACE_CONTRACT.md "Commercial activation transport API"
require_documented 'CommercialLicenseActivationService' docs/INTERFACE_CONTRACT.md "Commercial activation service API"
require_documented 'cancelPendingActivation' docs/INTERFACE_CONTRACT.md "Commercial activation cancellation contract"
require_documented 'latest-operation-wins' docs/INTERFACE_CONTRACT.md "Commercial activation concurrency contract"
require_documented '决策面替代该会话的普通可点击 TaskCard' docs/INTERFACE_CONTRACT.md "Focused action-request presentation contract"
require_documented '总数使用 `session/sessions`' docs/INTERFACE_CONTRACT.md "Expanded-panel session language contract"
require_documented 'case connected, configured, updateRequired, disconnected' docs/INTERFACE_CONTRACT.md "Codex trust-aware Hook status contract"
require_documented 'snapshotResolvingVendorActivation' docs/INTERFACE_CONTRACT.md "Vendor activation resolution API"
require_documented '2 MiB 上限' docs/INTERFACE_CONTRACT.md "Codex trust-probe bound contract"

require_documented 'reviewInAgent\(command: "/hooks"\)' IslandCore/Sources/IslandCore/Connectors/Codex/CodexAgent.swift "Codex vendor-owned trust gate"
require_documented 'case configured' IslandCore/Sources/IslandCore/Connectors/Framework/LocalAgentHookDiagnostics.swift "Configured Hook diagnostic state"

rg -q 'PRIVACY\.md' README.md || fail "README must link the canonical privacy notice"
rg -q 'TERMS\.md' README.md || fail "README must link the canonical terms"
rg -q 'DATA_FLOW_INVENTORY\.md' README.md || fail "README must link the data-flow inventory"
rg -q 'SECURITY\.md' README.md || fail "README must link the private security-reporting policy"
rg -q 'Codex `/hooks`' README.md || fail "README must distinguish Codex config from Hook trust"

require_documented 'security/advisories/new' SECURITY.md "Private GitHub advisory channel"
require_documented 'Do not include API keys' SECURITY.md "Secret-safe reporting guidance"

echo "Legal and data-flow invariants: PASS"
