import SwiftUI
import AppKit

/// Per-agent brand identity: real logo where we ship one, monogram
/// fallback everywhere else.
///
/// Logos are template PNGs (black on transparent) generated by
/// `scripts/make-agent-logos.swift` into `IslandApp/Resources/` and copied
/// into the bundle by `build-app.sh`. Template rendering lets each context
/// pick its own ink: white on the dark panel, label color in Settings.
///
/// The monogram fallback covers (a) sources we haven't shipped a logo for
/// yet — the roadmap wants 26+ agents — and (b) non-bundled contexts
/// (`swift run`, previews) where `NSImage(named:)` can't find the assets.
enum AgentBrand {
    /// Template logo for a task source, or `nil` when we don't ship one.
    /// Cached: NSImage(named:) already caches, but we also cache the
    /// misses so unknown sources don't re-hit the bundle on every row.
    @MainActor
    static func logo(for source: String) -> NSImage? {
        if let cached = cache[source] { return cached }
        let image = NSImage(named: "AgentLogo-\(source)")
        image?.isTemplate = true
        cache[source] = image
        return image
    }

    /// Monogram used when no logo asset exists for the source.
    static func monogram(for source: String) -> String {
        switch source {
        case "manus":       return "M"
        case "claude-code": return "C"
        case "codex":       return "Cx"
        case "cursor":      return "Cu"
        default:            return String(source.prefix(1)).uppercased()
        }
    }

    @MainActor
    private static var cache: [String: NSImage?] = [:]
}

/// Squircle-badged agent logo — the visual used in task cards and the
/// Settings service rows. Falls back to the monogram automatically.
struct AgentLogoBadge: View {
    let source: String
    /// Badge edge length. The glyph is inset ~62% of this.
    var size: CGFloat = 26
    /// Ink color for the template logo / monogram text.
    var ink: Color = .white.opacity(0.85)
    /// Badge background. Pass `nil` to render the bare glyph.
    var badge: Color? = Color.white.opacity(0.08)

    var body: some View {
        ZStack {
            if let badge {
                RoundedRectangle(cornerRadius: size * 0.27, style: .continuous)
                    .fill(badge)
                    .frame(width: size, height: size)
            }
            if let logo = AgentBrand.logo(for: source) {
                Image(nsImage: logo)
                    .renderingMode(.template)
                    .resizable()
                    .interpolation(.high)
                    .scaledToFit()
                    .frame(width: size * 0.62, height: size * 0.62)
                    .foregroundStyle(ink)
            } else {
                Text(AgentBrand.monogram(for: source))
                    .font(.system(size: size * 0.46, weight: .semibold, design: .rounded))
                    .foregroundStyle(ink)
            }
        }
        .frame(width: size, height: size)
    }
}

#if PREVIEWS && DEBUG
#Preview("Agent logo badges") {
    HStack(spacing: 10) {
        ForEach(["claude-code", "codex", "cursor", "manus", "opencode"], id: \.self) {
            AgentLogoBadge(source: $0)
        }
    }
    .padding(20)
    .background(Color.black)
}
#endif
