import SwiftUI
import AppKit

/// Per-agent brand identity: real logo where we ship one, monogram
/// fallback everywhere else.
///
/// Logos are template PNGs (black on transparent) generated by
/// `scripts/make-agent-logos.swift` into `IslandApp/Resources/` and copied
/// into the bundle by `build-app.sh`. Template rendering lets each context
/// pick its own ink: white on the dark panel, label color in Settings.
///
/// The monogram fallback covers (a) sources we haven't shipped a logo for
/// yet — the roadmap wants 26+ agents — and (b) non-bundled contexts
/// (`swift run`, previews) where `NSImage(named:)` can't find the assets.
enum AgentBrand {
    /// Template logo for a task source, or `nil` when we don't ship one.
    /// Cached: NSImage(named:) already caches, but we also cache the
    /// misses so unknown sources don't re-hit the bundle on every row.
    @MainActor
    static func logo(for source: String) -> NSImage? {
        if let cached = cache[source] { return cached }
        var image = NSImage(named: "AgentLogo-\(source)")
        #if DEBUG
        if image == nil, let resourceDirectoryOverride {
            image = NSImage(
                contentsOf: resourceDirectoryOverride
                    .appendingPathComponent("AgentLogo-\(source).png")
            )
        }
        #endif
        image?.isTemplate = true
        cache[source] = image
        return image
    }

    /// Monogram used when no logo asset exists for the source.
    static func monogram(for source: String) -> String {
        switch source {
        case "manus":       return "M"
        case "claude-code": return "C"
        case "codex":       return "Cx"
        case "cursor":      return "Cu"
        case "gemini-cli":  return "G"
        case "qwen-code":   return "Q"
        case "copilot-cli": return "Co"
        case "kimi-code":   return "K"
        case "opencode":    return "O"
        default:            return String(source.prefix(1)).uppercased()
        }
    }

    @MainActor
    private static var cache: [String: NSImage?] = [:]

    #if DEBUG
    /// Explicit test/preview resource root. Production always resolves from
    /// the signed app bundle; keeping this DEBUG-only prevents a runtime
    /// environment variable or arbitrary path from influencing brand assets.
    @MainActor
    static var resourceDirectoryOverride: URL? {
        didSet { cache.removeAll() }
    }
    #endif
}

/// Squircle-badged agent logo — the visual used in task cards and the
/// Settings service rows. Falls back to the monogram automatically.
struct AgentLogoBadge: View {
    let source: String
    /// Badge edge length. Each mark receives a small optical-size correction
    /// so dense silhouettes stay legible at menu-bar scale.
    var size: CGFloat = 26
    /// Ink color for the template logo / monogram text.
    var ink: Color = .white.opacity(0.85)
    /// Badge background. Pass `nil` to render the bare glyph.
    var badge: Color? = Color.white.opacity(0.08)

    var body: some View {
        ZStack {
            if let badge {
                RoundedRectangle(cornerRadius: size * 0.27, style: .continuous)
                    .fill(badge)
                    .frame(width: size, height: size)
            }
            if let logo = AgentBrand.logo(for: source) {
                Image(nsImage: logo)
                    .renderingMode(.template)
                    .resizable()
                    .interpolation(.high)
                    .scaledToFit()
                    .frame(width: size * glyphScale, height: size * glyphScale)
                    .foregroundStyle(resolvedInk)
            } else {
                Text(AgentBrand.monogram(for: source))
                    .font(.system(size: size * 0.46, weight: .semibold, design: .rounded))
                    .foregroundStyle(ink)
            }
        }
        .frame(width: size, height: size)
    }

    /// The supplied Codex mark has a dense 24×24 outline and an internal
    /// prompt glyph. At the generic 62% scale both details collapse into a
    /// soft blob, so it gets a restrained optical enlargement. The warm sand
    /// ink is the same accent used throughout Dev Island's tour and keeps the
    /// monochrome mark inside the product palette.
    private var glyphScale: CGFloat {
        switch source {
        case "codex":    return 0.72
        case "opencode": return 0.70
        default:          return 0.62
        }
    }

    private var resolvedInk: Color {
        source == "codex" ? Palette.tourAccent.opacity(0.96) : ink
    }
}

#if PREVIEWS && DEBUG
#Preview("Agent logo badges") {
    HStack(spacing: 10) {
        ForEach(["claude-code", "codex", "cursor", "gemini-cli", "qwen-code", "copilot-cli", "kimi-code", "manus", "opencode"], id: \.self) {
            AgentLogoBadge(source: $0)
        }
    }
    .padding(20)
    .background(Color.black)
}
#endif
